/*
 * This source file was generated by the Gradle 'init' task
 */
package java2assignment2;

public class App {    
    public static void main(String[] args) {
        AssetManager assetManager = new AssetManager();
        for (AssetType type : AssetType.values()) {
            Asset asset = AssetFactory.createAsset(type, "My");
            System.out.println("Created asset: " + asset.getName());
            assetManager.getAssetData(asset);
        }
    }
}