/*
 * This source file was generated by the Gradle 'init' task
 */
package java2assignment2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appCash() {
        Asset classUnderTest = AssetFactory.createAsset(AssetType.cash, "My");
        assertEquals(classUnderTest.getName(), "My " + AssetType.cash);
        assertEquals(classUnderTest.getType(), AssetType.cash);
    }
    @Test void appStock() {
        Asset classUnderTest = AssetFactory.createAsset(AssetType.stock, "My");
        assertEquals(classUnderTest.getName(), "My " + AssetType.stock);
        assertEquals(classUnderTest.getType(), AssetType.stock);
    }
    @Test void appHouse() {
        Asset classUnderTest = AssetFactory.createAsset(AssetType.house, "My");
        assertEquals(classUnderTest.getName(), "My " + AssetType.house);
        assertEquals(classUnderTest.getType(), AssetType.house);
    }
    @Test void appComputer() {
        Asset classUnderTest = AssetFactory.createAsset(AssetType.computer, "My");
        assertEquals(classUnderTest.getName(), "My " + AssetType.computer);
        assertEquals(classUnderTest.getType(), AssetType.computer);
    }
    @Test void appRefrigerator() {
        Asset classUnderTest = AssetFactory.createAsset(AssetType.refrigerator, "My");
        assertEquals(classUnderTest.getName(), "My " + AssetType.refrigerator);
        assertEquals(classUnderTest.getType(), AssetType.refrigerator);
    }
    @Test void appManager() {
        AssetManager classUnderTest = new AssetManager();
        classUnderTest.getAssetData(AssetFactory.createAsset(AssetType.computer, "My")); // This prints 2 lines to the console
        //Unsure how else to test this? Getting console output in tests seem like overkill for this assignment
    }
}